CeladonHouse1_MapScripts::
	.byte 0

CeladonHouse1_EventScript_Picnicker::
	msgbox CeladonHouse1_Text_Picnicker, MSGBOX_NPC
	end

CeladonHouse1_EventScript_Camper::
	msgbox CeladonHouse1_Text_Camper, MSGBOX_NPC
	end

CeladonHouse1_EventScript_Fisher::
	msgbox CeladonHouse1_Text_Fisher, MSGBOX_NPC
	end

CeladonHouse1_EventScript_Fisher2::
	msgbox CeladonHouse1_Text_Fisher2, MSGBOX_NPC
	end

CeladonHouse1_EventScript_Fisher3::
	msgbox CeladonHouse1_Text_Fisher3, MSGBOX_NPC
	end

CeladonHouse1_EventScript_Boy::
	msgbox CeladonHouse1_Text_Boy, MSGBOX_NPC
	end

CeladonHouse1_EventScript_Boy2::
	msgbox CeladonHouse1_Text_Boy2, MSGBOX_NPC
	end

CeladonHouse1_EventScript_Server::
	msgbox CeladonHouse1_Text_Server, MSGBOX_NPC
	end

CeladonHouse1_Text_Picnicker:
	.string "My boyfriend hates this place.$"

CeladonHouse1_Text_Camper:
	.string "This is our first date.$"

CeladonHouse1_Text_Fisher:
	.string "Ain't nothing beat eating a good meal\n"
	.string "after fishing on a bridge all day.$"

CeladonHouse1_Text_Fisher2:
	.string "The waitress sure is cute.$"

CeladonHouse1_Text_Fisher3:
	.string "I LOVE FISHING AHHH!!$"

CeladonHouse1_Text_Boy:
	.string "I wish I had a friend to sit with.$"

CeladonHouse1_Text_Boy2:
	.string "I'm lonely.$"

CeladonHouse1_Text_Server:
	.string "I wish that fisherman would stop\n"
	.string "eyeing me up.$"

