DaycareGarden_MapScripts::
	.byte 0

DaycareGarden_EventScript_GardenBlock::
	msgbox DaycareGarden_Text_RareMons, MSGBOX_NPC
	end

DaycareGarden_Text_RareMons:
	.string "Hello there.\p"
	.string "The area ahead is managed by Bill.\n"
	.string "The original creator of the PC.\p"
	.string "Rare Pokemon tend to gather back here,\n"
	.string "so Bill has blocked it off to only\l"
	.string "trainers who are strong enough.\p"
	.string "Try coming back when you are.$"

