#ifndef GUARD_CONSTANTS_HELP_WINDOW_H
#define GUARD_CONSTANTS_HELP_WINDOW_H

// Add new IDs here
enum {
    HELP_START_MENU,
    HELP_MEGA_EVOLUTION,
    HELP_MASTER_BALL,
    HELP_GIMMIGHOUL_COINS,
    HELP_QUEST_1_CATCH_REGIS,
    HELP_COUNT
};

#endif // GUARD_CONSTANTS_HELP_WINDOW_H
