#ifndef GUARD_CONSTANTS_QUESTS_H
#define GUARD_CONSTANTS_QUESTS_H

#define SIDE_QUEST_1  0
#define SIDE_QUEST_2  1
#define SIDE_QUEST_3  2
#define SIDE_QUEST_4  3
#define SIDE_QUEST_5  4
#define SIDE_QUEST_6  5
#define SIDE_QUEST_7  6
#define SIDE_QUEST_8  7
#define SIDE_QUEST_9  8
#define SIDE_QUEST_10 9
#define SIDE_QUEST_11 10
#define SIDE_QUEST_12 11
#define SIDE_QUEST_13 12
#define SIDE_QUEST_14 13
#define SIDE_QUEST_15 14
#define SIDE_QUEST_16 15
#define SIDE_QUEST_17 16
#define SIDE_QUEST_18 17
#define SIDE_QUEST_19 18
#define SIDE_QUEST_20 19
#define SIDE_QUEST_21 20
#define SIDE_QUEST_22 21
#define SIDE_QUEST_23 22
#define SIDE_QUEST_24 23
#define SIDE_QUEST_25 24
#define SIDE_QUEST_26 25
#define SIDE_QUEST_27 26
#define SIDE_QUEST_28 27
#define SIDE_QUEST_29 28
#define SIDE_QUEST_30 29

#define SIDE_QUEST_COUNT (SIDE_QUEST_30 + 1)
#define SIDE_QUEST_FLAGS_COUNT ((SIDE_QUEST_COUNT / 8) + ((SIDE_QUEST_COUNT % 8) ? 1 : 0))

#define QUEST_LINE_VISIBLE_COUNT 10

#define QUEST_FLAG_GET_UNLOCKED   0
#define QUEST_FLAG_SET_UNLOCKED   1
#define QUEST_FLAG_GET_COMPLETED  2
#define QUEST_FLAG_SET_COMPLETED  3

#define OAK_QUEST_STATE_NONE         0
#define OAK_QUEST_STATE_CATCH_REGIS  1
#define OAK_QUEST_STATE_STUDYING     2
#define OAK_QUEST_STATE_Q1_DONE      3

#endif // GUARD_CONSTANTS_QUESTS_H
