Route140_MapScripts::
	.byte 0

Route140_EventScript_Scientist1::
	msgbox Route140_Text_Scientist1, MSGBOX_NPC
	end

Route140_Text_Scientist1:
	.string "Professor Birch has nearly 80% of his\n"
	.string "staff out here.$"

Route140_EventScript_Scientist2::
	msgbox Route140_Text_Scientist2, MSGBOX_NPC
	end

Route140_Text_Scientist2:
	.string "Be careful, I saw members of Team\n"
	.string "Aqua, Magma, Strata, and Rocket\l"
	.string "past the Littleroot Woods.$"

Route140_EventScript_Scientist3::
	msgbox Route140_Text_Scientist3, MSGBOX_NPC
	end

Route140_Text_Scientist3:
	.string "Sky, Dash, Rye, and Jake are all\n"
	.string "exploring in the deeper routes.$"

Route140_EventScript_Scientist4::
	msgbox Route140_Text_Scientist4, MSGBOX_NPC
	end

Route140_Text_Scientist4:
	.string "The readings in the areas ahead\n"
	.string "are off the charts.$"

