#ifndef GUARD_GAME_CORNER_EXPANSION_H
#define GUARD_GAME_CORNER_EXPANSION_H

#define GAME_CORNER_VAR_ID_CHECK        VAR_ROUTE123_STATE
#define GAME_CORNER_VAR_WINNINGS        VAR_ROUTE124_STATE

#define FLAPPY_VAR_HIGH_SCORE        VAR_UNUSED_0x40FE

#define BLACKJACK_FLAG_INSURANCE    FLAG_UNUSED_0x493
#define BLACKJACK_FLAG_RESET        FLAG_UNUSED_0x494
#define BLACKJACK_FLAG_BLACKJACK    FLAG_UNUSED_0x495
#define BLACKJACK_VAR_PLAYER        VAR_ROUTE125_STATE
#define BLACKJACK_VAR_DEALER        VAR_ROUTE126_STATE
#define BLACKJACK_VAR_BET           VAR_ROUTE127_STATE
#define BLACKJACK_VAR_OPTIONS       VAR_ROUTE129_STATE
#define BLACKJACK_VAR_OPTION1_TILE  VAR_ROUTE130_STATE
#define BLACKJACK_VAR_OPTION2_TILE  VAR_ROUTE131_STATE
#define BLACKJACK_VAR_OPTION3_TILE  VAR_ROUTE132_STATE

#define DERBY_FLAG_NICKNAME             FLAG_UNUSED_0x496
#define DERBY_FLAG_RESET                FLAG_UNUSED_0x497
#define DERBY_VAR_RACER_NAME_1          VAR_ROUTE133_STATE
#define DERBY_VAR_RACER_NAME_2          VAR_ROUTE134_STATE
#define DERBY_VAR_RACER_NAME_3          VAR_UNUSED_0x408B
#define DERBY_VAR_RACER_NAME_4          VAR_UNUSED_0x4091
#define DERBY_VAR_RACER_NAME_5          VAR_UNUSED_0x40A1
#define DERBY_VAR_RACER_NAME_6          VAR_UNUSED_0x40A8
#define DERBY_VAR_RACER_1               VAR_UNUSED_0x40DB
#define DERBY_VAR_RACER_2               VAR_UNUSED_0x40DC
#define DERBY_VAR_RACER_3               VAR_UNUSED_0x40E5
#define DERBY_VAR_RACER_4               VAR_UNUSED_0x40FA
#define DERBY_VAR_RACER_5               VAR_UNUSED_0x40FB
#define DERBY_VAR_RACER_6               VAR_UNUSED_0x40FC

#define FLIP_VAR_LEVEL                  VAR_UNUSED_0x40FD

#endif // GUARD_GAME_CORNER_EXPANSION_H
