// Generated by tools/generate_region_map_assets.py
// Optional maps: graphics/pokenav/region_map/region_map_{2,3,4}.png
// Custom maps are converted to affine 8bpp, 64x64 8-bit tilemaps, and
// 48 colors at BG palette slot 7 (pixel indices 112-159).
#ifndef GUARD_REGION_MAP_EXTRA_ASSETS_H
#define GUARD_REGION_MAP_EXTRA_ASSETS_H

static const u16 sRegionMap2_Pal[] = INCBIN_U16("graphics/pokenav/region_map/region_map_2.gbapal");
static const u32 sRegionMap2_GfxLZ[] = INCBIN_U32("graphics/pokenav/region_map/region_map_2.8bpp.lz");
static const u32 sRegionMap2_TilemapLZ[] = INCBIN_U32("graphics/pokenav/region_map/region_map_2.bin.lz");
#define REGION_MAP_2_PAL sRegionMap2_Pal
#define REGION_MAP_2_GFX sRegionMap2_GfxLZ
#define REGION_MAP_2_TILEMAP sRegionMap2_TilemapLZ
static const u16 sRegionMap3_Pal[] = INCBIN_U16("graphics/pokenav/region_map/region_map_3.gbapal");
static const u32 sRegionMap3_GfxLZ[] = INCBIN_U32("graphics/pokenav/region_map/region_map_3.8bpp.lz");
static const u32 sRegionMap3_TilemapLZ[] = INCBIN_U32("graphics/pokenav/region_map/region_map_3.bin.lz");
#define REGION_MAP_3_PAL sRegionMap3_Pal
#define REGION_MAP_3_GFX sRegionMap3_GfxLZ
#define REGION_MAP_3_TILEMAP sRegionMap3_TilemapLZ
static const u16 sRegionMap4_Pal[] = INCBIN_U16("graphics/pokenav/region_map/region_map_4.gbapal");
static const u32 sRegionMap4_GfxLZ[] = INCBIN_U32("graphics/pokenav/region_map/region_map_4.8bpp.lz");
static const u32 sRegionMap4_TilemapLZ[] = INCBIN_U32("graphics/pokenav/region_map/region_map_4.bin.lz");
#define REGION_MAP_4_PAL sRegionMap4_Pal
#define REGION_MAP_4_GFX sRegionMap4_GfxLZ
#define REGION_MAP_4_TILEMAP sRegionMap4_TilemapLZ

#endif // GUARD_REGION_MAP_EXTRA_ASSETS_H
