MauvilleCity_StoneSeller_MapScripts::
	.byte 0

MauvilleCity_StoneSeller_EventScript_SellStones::
	lock
	faceplayer
	msgbox MauvilleCity_StoneSeller_Text_Hello, MSGBOX_DEFAULT
	waitmessage
	pokemart StoneSeller_Mart_Pokemart
	msgbox MauvilleCity_StoneSeller_Text_SeeYa, MSGBOX_DEFAULT
	release
	end

	.align 2
StoneSeller_Mart_Pokemart:
	.2byte ITEM_DEEP_SEA_SCALE
	.2byte ITEM_DEEP_SEA_TOOTH
	.2byte ITEM_DUBIOUS_DISC
	.2byte ITEM_ELECTIRIZER
	.2byte ITEM_MAGMARIZER
	.2byte ITEM_KINGS_ROCK
	.2byte ITEM_METAL_COAT
	.2byte ITEM_OVAL_STONE
	.2byte ITEM_PRISM_SCALE
	.2byte ITEM_PROTECTOR
	.2byte ITEM_RAZOR_CLAW
	.2byte ITEM_RAZOR_FANG
	.2byte ITEM_REAPER_CLOTH
	.2byte ITEM_SACHET
	.2byte ITEM_UPGRADE
	.2byte ITEM_WHIPPED_DREAM
	.2byte ITEM_AUSPICIOUS_ARMOR
	.2byte ITEM_BLACK_AUGURITE
	.2byte ITEM_CHIPPED_POT
	.2byte ITEM_CRACKED_POT
	.2byte ITEM_GALARICA_CUFF
	.2byte ITEM_MALICIOUS_ARMOR
	.2byte ITEM_MASTERPIECE_TEACUP
	.2byte ITEM_METAL_ALLOY
	.2byte ITEM_PEAT_BLOCK
	.2byte ITEM_SCROLL_OF_DARKNESS
	.2byte ITEM_SCROLL_OF_WATERS
	.2byte ITEM_SWEET_APPLE
	.2byte ITEM_SYRUPY_APPLE
	.2byte ITEM_TART_APPLE
	.2byte ITEM_UNREMARKABLE_TEACUP
	.2byte ITEM_FIRE_STONE
	.2byte ITEM_WATER_STONE
	.2byte ITEM_THUNDER_STONE
	.2byte ITEM_LEAF_STONE
	.2byte ITEM_MOON_STONE
	.2byte ITEM_SUN_STONE
	.2byte ITEM_SHINY_STONE
	.2byte ITEM_DUSK_STONE
	.2byte ITEM_DAWN_STONE
	.2byte ITEM_ICE_STONE
	.2byte ITEM_NONE
	release
	end

MauvilleCity_StoneSeller_Text_Hello:
	.string "Hi there, what would you like?$"

MauvilleCity_StoneSeller_Text_SeeYa:
	.string "Come again.$"

