VermillionCity_MapScripts::
	.byte 0

VermillionCity_EventScript_Locked::
	msgbox VermillionCity_Text_Locked, MSGBOX_SIGN
	end

VermillionCity_Text_Locked:
	.string "It's locked.$"

VermillionCity_EventScript_Snorlax::
	msgbox VermillionCity_Text_SleepingSnorlax, MSGBOX_NPC
	end

VermillionCity_Text_SleepingSnorlax:
	.string "It's a sleeping Snorlax!\p"
	.string "How original.\p"
	.string "Too bad you don't have a flute.$"

VermillionCity_EventScript_Hotel::
	msgbox VermillionCity_Text_Hotel, MSGBOX_SIGN
	end

VermillionCity_Text_Hotel:
	.string "VERMILLION HOTEL:\n"
	.string "OPEN SOON$"

VermillionCity_EventScript_MachampMan::
	msgbox VermillionCity_Text_MachampMan, MSGBOX_NPC
	end

VermillionCity_Text_MachampMan:
	.string "I started building this with my\n"
	.string "trusty Machop.\p"
	.string "Now, he's become a big Machamp!$"

VermillionCity_EventScript_HotelWoman::
	msgbox VermillionCity_Text_HotelWoman, MSGBOX_NPC
	end

VermillionCity_Text_HotelWoman:
	.string "Hello, we aren't quite open yet.\p"
	.string "Please come back when we are.$"

VermillionCity_EventScript_CitySign::
	msgbox VermillionCity_Text_CitySign, MSGBOX_SIGN
	end

VermillionCity_Text_CitySign:
	.string "VERMILLION CITY:\p"
	.string "NOT MUCH GOING ON$"

VermillionCity_EventScript_FanClubSign::
	msgbox VermillionCity_Text_FanClubSign, MSGBOX_SIGN
	end

VermillionCity_Text_FanClubSign:
	.string "POKEMON FAN CLUB:\p"
	.string "WE <3 RAPIDASH$"

VermillionCity_EventScript_GymSign::
	msgbox VermillionCity_Text_GymSign, MSGBOX_SIGN
	end

VermillionCity_Text_GymSign:
	.string "VERMILLION CITY GYM:\p"
	.string "HOME OF THE WAR HERO$"

VermillionCity_EventScript_Fisher1::
	msgbox VermillionCity_Text_Fisher1, MSGBOX_NPC
	end

VermillionCity_Text_Fisher1:
	.string "Only Magikarp today.\p"
	.string "Only Magikarp always...$"

VermillionCity_EventScript_Fisher2::
	msgbox VermillionCity_Text_Fisher2, MSGBOX_NPC
	end

VermillionCity_Text_Fisher2:
	.string "You came from Hoenn?\p"
	.string "That's pretty far!$"

VermillionCity_EventScript_Boy::
	msgbox VermillionCity_Text_Boy, MSGBOX_NPC
	end

VermillionCity_Text_Boy:
	.string "Why is my house backwards?$"

VermillionCity_EventScript_Lass::
	msgbox VermillionCity_Text_Lass, MSGBOX_NPC
	end

VermillionCity_Text_Lass:
	.string "I'm exercising!$"

VermillionCity_EventScript_FanClubPresident::
	msgbox VermillionCity_Text_FanClubPresident, MSGBOX_NPC
	end

VermillionCity_Text_FanClubPresident:
	.string "Our club is ruined!\p"
	.string "The police came and arrested over\n"
	.string "half our members!\p"
	.string "Those poor Lopunny and Gardevoir\n"
	.string "have no trainers now...$"

VermillionCity_EventScript_GuitarGuy::
	msgbox VermillionCity_Text_GuitarGuy, MSGBOX_NPC
	end

VermillionCity_Text_GuitarGuy:
	.string "Surge is in Hoenn right now at\n"
	.string "the Champion club.\p"
	.string "It's so boring when gym season\n"
	.string "isn't happening.$"

